name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup OpenCV
        run: sudo apt update
        run: sudo apt install libopencv-dev
#        uses: Dovyski/setup-opencv-action@v1
#        with:
#          opencv-version: 4.0.0
#          opencv-extra-modules: false
#          install-deps: true
#          CMAKE_BUILD_TYPE: RELEASE
#          WITH_OPENGL: false
#          BUILD_NEW_PYTHON_SUPPORT: false
      - name: Setup OpenCL
        run: sudo apt update
        run: sudo apt install ocl-icd-* opencl-headers
      - name: Make OCL DaMa
        run: cmake -S . -B build
      - name: Build OCL DaMA
        run: cmake --build build --config Release
