name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup OpenCV
        uses: Dovyski/setup-opencv-action@v1
        with:
          opencv-version: 4.0.0
          opencv-extra-modules: true
          install-deps: true
          CMAKE_BUILD_TYPE: RELEASE
          WITH_OPENGL: true
          BUILD_NEW_PYTHON_SUPPORT: false
      - name: configure
        run: cmake .
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
